### PR TITLE
Accept piped input

### LINKED ISSUE #18: add feature to pipe stdin
Makes it super easy to pipe something and get a qr code:

`echo 'foobar' | qrcode-terminal`

This is useful if you have a command that outputs something you want to scan with a mobile phone.

### PR DESCRIPTION
**Pull request by kblum**
This pull request makes it possible to generate QR Codes by piping data to the CLI tool.

Accepting input as argument (standard usage):

``` sh
./bin/qrcode-terminal.js 'http://github.com'
```

qrcode-terminal-argument

Accepting piped input:

``` sh
echo 'http://github.com' | ./bin/qrcode-terminal.js
```

qrcode-terminal-pipe

Fixes #18

### CODE REVIEW

**Comment by siddhartpai** [comment]
This is a great pull request, @gtanner Can you please merge this off and release a better version of qr-code terminal

**Comment by mwbrooks** [comment]
Hey @kblum and @siddhartpai, I think this PR looks great as well. Works locally and tests all pass.

I still have commit and npm access, so I'll cut a release for you!

**Comment by mwbrooks** [comment]
Published on npm as qrcode-terminal@0.12.0
https://www.npmjs.com/package/qrcode-terminal

Thanks again @kblum 💯

**Comment by gtanner** [comment]
Awesome!

Thanks

________________________________

**Pull request merged**
