### PR TITLE
Small qrcode output

### PR DESCRIPTION
**Pull request by goorockey**
Support small qrcode output by combine adjacent row and using unicode character.

Screenshot:

small_qr

Related issue: #9

### CODE REVIEW

**Comment by mwbrooks** [comment]
This is really awesome @goorockey!

I think I'd prefer the small QRCode to be the default on. What do you think @gtanner?

**Comment by gtanner** [comment]
I like the small one for the default as well. @mwbrooks, @goorockey.

I will merge this in and bundle up a release :)

**Comment by gtanner** [comment]
Small seems distorted to me.
screen shot 2015-11-17 at 11 30 26 am

**Comment by mwbrooks** [comment]
Same :( with 13pt Source Code Pro font.

screen shot 2015-11-17 at 9 03 55 am

**Comment by gtanner** [comment]
Thoughts?

Sadly I merged this in blind :(  I didn't publish so isn't that bad.

I could roll back or rebase out the commit, or leave it in while we figure out a good way to get the small version working.

**Comment by mwbrooks** [comment]
No bright ideas on my end. @goorockey?

**Comment by goorockey** [comment]
According to [unicode standard](http://www.unicode.org/versions/Unicode6.2.0/ch15.pdf#page=30), there should not be gaps.

> When emulating terminal applications, fonts that implement the block element characters should be designed so that adjacent glyphs for characters such as U+2588 full block create solid patterns with no gaps between them.

So I consider it's the issue of fonts that don't implement block elements correctly.

Anyway, the distorted qrcode can still be decoded correctly. :joy:

**Comment by goorockey** [comment]
I think it's reasonable to notice in README that the small qrcode depends on the font that you are using.

**Pull request merged**
